language: 
  - php 

services:
  - mongodb

php:
  - 5.5
  - 5.4

env:
  - CI_ENVIRONMENT="travis"

install:
 - composer install
 
before_script:
  - composer install

notifications:
  email:
    - andy.potanin@usabilitydynamics.com
  webhooks: 
    - http://your-domain.com/notifications
